export const IS_LOADING = 'IS_LOADING';
export const IS_LOGIN_LOADING = 'IS_LOGIN_LOADING';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';
export const FORGOT_SUCCESS = 'FORGOT_SUCCESS';
export const FORGOT_FAILED = 'FORGOT_FAILED';
export const IS_AUTH_SUCCESS = 'IS_AUTH_SUCCESS';
export const IS_AUTH_FAILED = 'IS_AUTH_FAILED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';
export const PROFILE_IMAGE_SUCCESS = 'PROFILE_IMAGE_SUCCESS';
export const PROFILE_IMAGE_FAILED = 'PROFILE_IMAGE_FAILED';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';


export const GET_LOTTRY_SUCCESS = 'GET_LOTTRY_SUCCESS';
export const GET_LOTTRY_FAILED = 'GET_LOTTRY_FAILED';

export const GET_LOTTRY_HISTORY_SUCCESS = 'GET_LOTTRY_HISTORY_SUCCESS';
export const GET_LOTTRY_HISTORY_FAILED = 'GET_LOTTRY_HISTORY_FAILED';

export const GET_CUSTOMER_TICKET_SUCCESS = 'GET_CUSTOMER_TICKET_SUCCESS';
export const GET_CUSTOMER_TICKET_FAILED = 'GET_CUSTOMER_TICKET_FAILED';

export const GET_LOTTRY_DETAILS_SUCCESS = 'GET_LOTTRY_DETAILS_SUCCESS';
export const GET_LOTTRY_DETAILS_FAILED = 'GET_LOTTRY_DETAILS_FAILED';


export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';


export const CHANGE_USER_PASSWORD_SUCCESS = 'CHANGE_USER_PASSWORD_SUCCESS';
export const CHANGE_USER_PASSWORD_FAILED = 'CHANGE_USER_PASSWORD_FAILED';


export const GET_SETTING_SUCCESS = 'GET_SETTING_SUCCESS';
export const GET_SETTING_FAILED = 'GET_SETTING_FAILED';

export const SELECT_LANGUAGE = 'SELECT_LANGUAGE';

export const GET_WALLET_TRANSACTION_SUCCESS = 'GET_WALLET_TRANSACTION_SUCCESS';
export const GET_WALLET_TRANSACTION_FAILED = 'GET_WALLET_TRANSACTION_FAILED';