import LocalizedStrings from 'react-native-localization';

const StringsOfLanguages = new LocalizedStrings({
    en: {
        "jackpotPending": "Jackpot Pending",
        userName: 'Name',
        email: 'Email',
        password: 'Password',
        phoneNumber: 'Phone Number',
        country: 'Country',
        editProfile: 'Edit Profile',
        chooseLine: 'Choose the number of lines',
        systematic: 'Systematic',
        pickYourNumber: 'Pick Your Numbers',
        quickPlay: 'Quick Play',
        viewYourNumber: 'View Your Number',
        entry: 'Pick Your entry type below',
        play: 'Play',
        oneTimeEntry: 'One-Time Entry',
        lines: 'Lines',
        selectLanguage: 'Choose Your Language:',
        english: 'English',
        chinese: 'Chinese',
        korean: 'Korean',
        japanese: 'Japanese',
        vietnamese: 'Vietnamese',
        filipino: 'Filipino',
        malay: 'Malay',
        hindi: 'Hindi',
        indonesia: 'Bahasa Indonesia',
        chooseImage: "Change Picture",
        changePassword: 'Change Password',
        deleteAccount: 'Delete Account',
        saveChanges: 'Save Changes',
        submit: 'Submit',
        aboutTitle: 'About Us',
        languageTitle: 'Language',
        userTransactionDone: 'User Done the transaction',
        ticketsTitle: 'Tickets',
        myWallet: 'My Wallet',
        myAccount: 'My Account',
        logout: 'Log Out',
        createAccoun: 'Create Account',
        logIn: 'Log In',
        emailPaceholder: 'E-mail',
        forgotPassword: 'Forgot Password',
        million: 'Millions',
        fullName: 'Full Name',
        userTransactionCancel: 'User Cancel the transaction',
        comfirmPassword: 'Confirm Password',
        signUp: 'Sign up',
        alreadyAccount: 'Already have an account',
        forgotHeading: ' Enter the email you use to login to Lottery and we will send you a link to get you back into your account.',
        couponCode: 'Coupon code',
        applyCoupon: 'Apply Coupon',
        symbol: '$',
        priceSummary: 'Price Summary',
        subTotal: 'Sub Total',
        discount: 'Discount',
        serviceFee: 'Service Fees',
        total: 'Total',
        "waiting_msg": "This drawing is now over. Wait for the next draw, please."
    },
    ko: {
        "jackpotPending": "잭팟 대기 중",
        "userName": "이름",
        "email": "이메일",
        "password": "비밀번호",
        "phoneNumber": "전화번호",
        "country": "국가",
        "editProfile": "프로필 편집",
        "chooseLine": "라인 수 선택",
        "systematic": "시스템식",
        "pickYourNumber": "번호 선택",
        "quickPlay": "빠른 플레이",
        "viewYourNumber": "번호 보기",
        "entry": "아래에서 엔트리 유형 선택",
        "play": "플레이",
        "oneTimeEntry": "일회성 엔트리",
        "lines": "라인",
        "selectLanguage": "언어 선택:",
        "english": "영어",
        "chinese": "중국어",
        "korean": "한국어",
        "japanese": "일본어",
        "vietnamese": "베트남어",
        "filipino": "필리핀어",
        "malay": "말레이어",
        "hindi": "힌디어",
        "indonesia": "인도네시아어",
        "chooseImage": "사진 변경",
        "changePassword": "비밀번호 변경",
        "deleteAccount": "계정 삭제",
        "saveChanges": "변경 사항 저장",
        "submit": "제출",
        "aboutTitle": "회사 소개",
        "languageTitle": "언어",
        "userTransactionDone": "사용자가 거래를 완료했습니다",
        "ticketsTitle": "티켓",
        "myWallet": "내 지갑",
        "myAccount": "내 계정",
        "logout": "로그아웃",
        "createAccount": "계정 생성",
        "logIn": "로그인",
        "emailPlaceholder": "이메일",
        "forgotPassword": "비밀번호를 잊으셨나요",
        "million": "백만",
        "fullName": "전체 이름",
        "userTransactionCancel": "사용자가 거래를 취소했습니다",
        "confirmPassword": "비밀번호 확인",
        "signUp": "가입하기",
        "alreadyAccount": "이미 계정이 있으신가요",
        "forgotHeading": "로또에 로그인하는 데 사용하는 이메일을 입력하시면 계정으로 돌아갈 수 있는 링크를 보내드립니다.",
        "couponCode": "쿠폰 코드",
        "applyCoupon": "쿠폰 적용",
        "symbol": "₩",
        "priceSummary": "가격 요약",
        "subTotal": "소계",
        "discount": "할인",
        "serviceFee": "서비스 수수료",
        "total": "총액",
        "waiting_msg": "이 추첨은 종료되었습니다. 다음 추첨을 기다려 주세요."
    },
    hi: {
        "jackpotPending": "जैकपॉट प्रलंबित है",
        "userName": "नाम",
        "email": "ईमेल",
        "password": "पासवर्ड",
        "phoneNumber": "फोन नंबर",
        "country": "देश",
        "editProfile": "प्रोफ़ाइल संपादित करें",
        "chooseLine": "लाइनों की संख्या चुनें",
        "systematic": "सिस्टमातिक",
        "pickYourNumber": "अपने नंबर चुनें",
        "quickPlay": "फ़ास्ट प्ले",
        "viewYourNumber": "अपने नंबर देखें",
        "entry": "नीचे अपने एंट्री प्रकार को चुनें",
        "play": "खेलें",
        "oneTimeEntry": "एक बार की एंट्री",
        "lines": "लाइनें",
        "selectLanguage": "अपनी भाषा चुनें:",
        "english": "अंग्रेज़ी",
        "chinese": "चीनी",
        "korean": "कोरियाई",
        "japanese": "जापानी",
        "vietnamese": "वियतनामी",
        "filipino": "फ़िलिपीनो",
        "malay": "मलय",
        "hindi": "हिंदी",
        "indonesia": "इंडोनेशियाई",
        "chooseImage": "तस्वीर बदलें",
        "changePassword": "पासवर्ड बदलें",
        "deleteAccount": "खाता हटाएं",
        "saveChanges": "बदलाव सहेजें",
        "submit": "सबमिट करें",
        "aboutTitle": "हमारे बारे में",
        "languageTitle": "भाषा",
        "userTransactionDone": "उपयोगकर्ता ने लेन-देन पूरा किया है",
        "ticketsTitle": "टिकट",
        "myWallet": "मेरा बटुआ",
        "myAccount": "मेरा खाता",
        "logout": "लॉग आउट",
        "createAccount": "खाता बनाएं",
        "logIn": "लॉग इन करें",
        "emailPaceholder": "ईमेल",
        "forgotPassword": "पासवर्ड भूल गए",
        "million": "लाख",
        "fullName": "पूरा नाम",
        "userTransactionCancel": "उपयोगकर्ता ने लेन-देन रद्द कर दिया है",
        "confirmPassword": "पासवर्ड की पुष्टि करें",
        "signUp": "साइन अप करें",
        "alreadyAccount": "पहले से ही खाता है",
        "forgotHeading": "लॉटरी में लॉग इन करने के लिए आपके द्वारा उपयोग किए जाने वाले ईमेल पते दर्ज करें और हम आपको एक लिंक भेजेंगे जो आपको अपने खाते में वापस ले जाएगा।",
        "couponCode": "कूपन कोड",
        "applyCoupon": "कूपन लागू करें",
        "symbol": "₹",
        "priceSummary": "मूल्य सारांश",
        "subTotal": "उप-योग",
        "discount": "डिस्काउंट",
        "serviceFee": "सेवा शुल्क",
        "total": "कुल",
        "waiting_msg": "यह ड्रा अब समाप्त हो गया है। कृपया अगले खींच के लिए प्रतीक्षा करें।"
    },
    ja: {
        "jackpotPending": "ジャックポット保留中",
        "userName": "名前",
        "email": "メール",
        "password": "パスワード",
        "phoneNumber": "電話番号",
        "country": "国",
        "editProfile": "プロフィールの編集",
        "chooseLine": "ラインの数を選択",
        "systematic": "システマティック",
        "pickYourNumber": "自分の番号を選ぶ",
        "quickPlay": "クイックプレイ",
        "viewYourNumber": "自分の番号を表示",
        "entry": "以下からエントリータイプを選んでください",
        "play": "プレイ",
        "oneTimeEntry": "ワンタイムエントリー",
        "lines": "ライン数",
        "selectLanguage": "言語を選択してください:",
        "english": "英語",
        "chinese": "中国語",
        "korean": "韓国語",
        "japanese": "日本語",
        "vietnamese": "ベトナム語",
        "filipino": "フィリピノ語",
        "malay": "マレー語",
        "hindi": "ヒンディー語",
        "indonesia": "インドネシア語",
        "chooseImage": "画像を変更する",
        "changePassword": "パスワードを変更する",
        "deleteAccount": "アカウントを削除する",
        "saveChanges": "変更内容を保存する",
        "submit": "送信",
        "aboutTitle": "私たちについて",
        "languageTitle": "言語",
        "userTransactionDone": "ユーザーが取引を完了しました",
        "ticketsTitle": "チケット",
        "myWallet": "マイウォレット",
        "myAccount": "マイアカウント",
        "logout": "ログアウト",
        "createAccount": "アカウントを作成する",
        "logIn": "ログイン",
        "emailPlaceholder": "メール",
        "forgotPassword": "パスワードをお忘れですか",
        "million": "百万",
        "fullName": "フルネーム",
        "userTransactionCancel": "ユーザーが取引をキャンセルしました",
        "confirmPassword": "パスワードを確認する",
        "signUp": "サインアップ",
        "alreadyAccount": "すでにアカウントをお持ちですか",
        "forgotHeading": "Lotteryにログインするために使用するメールアドレスを入力してください。アカウントに戻るためのリンクをお送りします。",
        "couponCode": "クーポンコード",
        "applyCoupon": "クーポンを適用する",
        "symbol": "＄",
        "priceSummary": "価格の概要",
        "subTotal": "小計",
        "discount": "割引",
        "serviceFee": "サービス料金",
        "total": "合計",
        "waiting_msg": "この抽選は終了しました。次の抽選をお待ちください。"
      },
    vi: {
        "jackpotPending": "Đang chờ Jackpot",
        "userName": "Tên",
        "email": "Email",
        "password": "Mật khẩu",
        "phoneNumber": "Số điện thoại",
        "country": "Quốc gia",
        "editProfile": "Chỉnh sửa hồ sơ",
        "chooseLine": "Chọn số dòng",
        "systematic": "Hệ thống",
        "pickYourNumber": "Chọn số của bạn",
        "quickPlay": "Chơi nhanh",
        "viewYourNumber": "Xem số của bạn",
        "entry": "Chọn loại tham gia dưới đây",
        "play": "Chơi",
        "oneTimeEntry": "Tham gia một lần",
        "lines": "Dòng",
        "selectLanguage": "Chọn ngôn ngữ của bạn:",
        "english": "Tiếng Anh",
        "chinese": "Tiếng Trung",
        "korean": "Tiếng Hàn",
        "japanese": "Tiếng Nhật",
        "vietnamese": "Tiếng Việt",
        "filipino": "Tiếng Philipin",
        "malay": "Tiếng Mã Lai",
        "hindi": "Tiếng Hindi",
        "indonesia": "Tiếng Indonesia",
        "chooseImage": "Thay đổi ảnh",
        "changePassword": "Thay đổi mật khẩu",
        "deleteAccount": "Xóa tài khoản",
        "saveChanges": "Lưu thay đổi",
        "submit": "Gửi",
        "aboutTitle": "Về chúng tôi",
        "languageTitle": "Ngôn ngữ",
        "userTransactionDone": "Người dùng đã hoàn tất giao dịch",
        "ticketsTitle": "Vé",
        "myWallet": "Ví của tôi",
        "myAccount": "Tài khoản của tôi",
        "logout": "Đăng xuất",
        "createAccoun": "Tạo tài khoản",
        "logIn": "Đăng nhập",
        "emailPaceholder": "Email",
        "forgotPassword": "Quên mật khẩu",
        "million": "Triệu",
        "fullName": "Họ và tên đầy đủ",
        "userTransactionCancel": "Người dùng đã hủy giao dịch",
        "comfirmPassword": "Xác nhận mật khẩu",
        "signUp": "Đăng ký",
        "alreadyAccount": "Đã có tài khoản",
        "forgotHeading": "Nhập email bạn sử dụng để đăng nhập vào Lottery và chúng tôi sẽ gửi cho bạn một liên kết để khôi phục tài khoản của bạn.",
        "couponCode": "Mã giảm giá",
        "applyCoupon": "Áp dụng mã giảm giá",
        "symbol": "$",
        "priceSummary": "Tóm tắt giá",
        "subTotal": "Tổng phụ",
        "discount": "Giảm giá",
        "serviceFee": "Phí dịch vụ",
        "total": "Tổng cộng",
        "waiting_msg": "Vòng quay này đã kết thúc. Vui lòng đợi vòng quay tiếp theo."
    },
    fil:{
        "jackpotPending": "Naghihintay ang Jackpot",
        "userName": "Pangalan",
        "email": "Email",
        "password": "Password",
        "phoneNumber": "Numero ng Telepono",
        "country": "Bansa",
        "editProfile": "I-edit ang Profile",
        "chooseLine": "Piliin ang bilang ng mga linya",
        "systematic": "Systematic",
        "pickYourNumber": "Pumili ng Iyong mga Numero",
        "quickPlay": "Mabilis na Paglaro",
        "viewYourNumber": "Tingnan ang Iyong Numero",
        "entry": "Pumili ng uri ng pagpasok sa ibaba",
        "play": "Maglaro",
        "oneTimeEntry": "Pang-isang Pagpasok",
        "lines": "Mga Linya",
        "selectLanguage": "Piliin ang Iyong Wika:",
        "english": "Ingles",
        "chinese": "Tsino",
        "korean": "Koreano",
        "japanese": "Hapones",
        "vietnamese": "Biyetnam",
        "filipino": "Filipino",
        "malay": "Malay",
        "hindi": "Hindi",
        "indonesia": "Bahasa Indonesia",
        "chooseImage": "Baguhin ang Larawan",
        "changePassword": "Baguhin ang Password",
        "deleteAccount": "Tanggalin ang Account",
        "saveChanges": "I-save ang mga Pagbabago",
        "submit": "Ipasa",
        "aboutTitle": "Tungkol sa Amin",
        "languageTitle": "Wika",
        "userTransactionDone": "Tapos na ang transaksyon ng User",
        "ticketsTitle": "Mga Tiket",
        "myWallet": "Aking Wallet",
        "myAccount": "Aking Account",
        "logout": "Mag-logout",
        "createAccount": "Lumikha ng Account",
        "logIn": "Mag-log In",
        "emailPlaceholder": "E-mail",
        "forgotPassword": "Nakalimutan ang Password",
        "million": "Milyon",
        "fullName": "Buong Pangalan",
        "userTransactionCancel": "Binawi ng User ang transaksyon",
        "confirmPassword": "Kumpirmahin ang Password",
        "signUp": "Mag-sign up",
        "alreadyAccount": "Mayroon nang account",
        "forgotHeading": "Maglagay ng email na ginagamit mo sa pag-login sa Lottery at kami ay magpapadala sa iyo ng link upang maibalik ang iyong account.",
        "couponCode": "Kupon code",
        "applyCoupon": "Mag-apply ng Kupon",
        "symbol": "₱",
        "priceSummary": "Suliranin sa Presyo",
        "subTotal": "Kabuuang Halaga",
        "discount": "Diskwento",
        "serviceFee": "Serbisyo Fees",
        "total": "Kabuuan",
        "waiting_msg": "Ang pagsasagawa na ito ay tapos na. Mangyaring maghintay para sa susunod na taya."
      },
    ms: {
      "jackpotPending": "Jackpot Menunggu",
      "userName": "Nama",
      "email": "E-mel",
      "password": "Kata Laluan",
      "phoneNumber": "Nombor Telefon",
      "country": "Negara",
      "editProfile": "Edit Profil",
      "chooseLine": "Pilih jumlah baris",
      "systematic": "Sistematik",
      "pickYourNumber": "Pilih Nombor Anda",
      "quickPlay": "Main Cepat",
      "viewYourNumber": "Lihat Nombor Anda",
      "entry": "Pilih jenis penyertaan anda di bawah",
      "play": "Main",
      "oneTimeEntry": "Penyertaan Satu Kali",
      "lines": "Baris",
      "selectLanguage": "Pilih Bahasa Anda:",
      "english": "Bahasa Inggeris",
      "chinese": "Bahasa Cina",
      "korean": "Bahasa Korea",
      "japanese": "Bahasa Jepun",
      "vietnamese": "Bahasa Vietnam",
      "filipino": "Bahasa Filipina",
      "malay": "Bahasa Melayu",
      "hindi": "Bahasa Hindi",
      "indonesia": "Bahasa Indonesia",
      "chooseImage": "Tukar Gambar",
      "changePassword": "Tukar Kata Laluan",
      "deleteAccount": "Padam Akaun",
      "saveChanges": "Simpan Perubahan",
      "submit": "Hantar",
      "aboutTitle": "Tentang Kami",
      "languageTitle": "Bahasa",
      "userTransactionDone": "Pengguna Telah Melakukan Transaksi",
      "ticketsTitle": "Tiket",
      "myWallet": "Dompet Saya",
      "myAccount": "Akaun Saya",
      "logout": "Log Keluar",
      "createAccount": "Buka Akaun",
      "logIn": "Log Masuk",
      "emailPlaceholder": "E-mel",
      "forgotPassword": "Lupa Kata Laluan",
      "million": "Jutaan",
      "fullName": "Nama Penuh",
      "userTransactionCancel": "Pengguna Membatalkan Transaksi",
      "confirmPassword": "Sahkan Kata Laluan",
      "signUp": "Daftar",
      "alreadyAccount": "Sudah mempunyai akaun",
      "forgotHeading": "Masukkan e-mel yang anda gunakan untuk log masuk ke Loteri dan kami akan menghantar anda pautan untuk mendapatkan semula akaun anda.",
      "couponCode": "Kod Kupon",
      "applyCoupon": "Guna Kupon",
      "symbol": "$",
      "priceSummary": "Ringkasan Harga",
      "subTotal": "Jumlah Keseluruhan",
      "discount": "Diskaun",
      "serviceFee": "Yuran Perkhidmatan",
      "total": "Jumlah",
      "waiting_msg": "Pertandingan ini sudah berakhir. Sila tunggu untuk cabutan seterusnya."
    },
    zh: {
        "jackpotPending": "累積獎金待定",
        "userName": "名字",
        "email": "電子郵件",
        "password": "密碼",
        "phoneNumber": "電話號碼",
        "country": "國家",
        "editProfile": "編輯個人資料",
        "chooseLine": "選擇行數",
        "systematic": "系統",
        "pickYourNumber": "選擇您的號碼",
        "quickPlay": "快速播放",
        "viewYourNumber": "查看您的號碼",
        "entry": "在下面選擇您的參賽作品類型",
        "play": "玩",
        "oneTimeEntry": "一次性入場",
        "lines": "線",
        "selectLanguage": "選擇您的語言：",
        "english": "英語",
        "chinese": "中文",
        "korean": "朝鮮語",
        "japanese": "日語",
        "vietnamese": "越南文",
        "filipino": "菲律賓文",
        "malay": "馬來語",
        "hindi": "不",
        "indonesia": "印尼文",
        "chooseImage": "更改圖片",
        "changePassword": "更改密碼",
        "deleteAccount": "刪除帳戶",
        "saveChanges": "保存更改",
        "submit": "提交",
        "aboutTitle": "關於我們",
        "languageTitle": "語言",
        "userTransactionDone": "使用者完成交易",
        "ticketsTitle": "票",
        "myWallet": "我的錢包",
        "myAccount": "我的帳戶",
        "logout": "註銷",
        "createAccoun": "創建帳戶",
        "logIn": "登錄",
        "emailPaceholder": "電子郵件",
        "forgotPassword": "忘記密碼",
        "million": "百萬",
        "fullName": "全名",
        "userTransactionCancel": "使用者取消交易",
        "comfirmPassword": "確認密碼",
        "signUp": "登記",
        "alreadyAccount": "已有帳戶",
        "forgotHeading": "輸入您用於登錄彩票的電子郵件，我們將向您發送一個連結，讓您重新進入您的帳戶。",
        "couponCode": "優惠券代碼",
        "applyCoupon": "申請優惠券",
        "symbol": "$",
        "priceSummary": "價格摘要",
        "subTotal": "小計",
        "discount": "折扣",
        "serviceFee": "服務費",
        "total": "總",
        "waiting_msg": "這幅畫到此結束。請等待下一次抽獎。"
    },
    id:{
        "jackpotPending":"Jackpot Menunggu",
        "userName":"Nama",
        "email":"Email",
        "password":"Kata Sandi",
        "phoneNumber":"Nomor Telepon",
        "country":"Negara",
        "editProfile":"Edit Profil",
        "chooseLine":"Pilih jumlah baris",
        "systematic":"Sistematik",
        "pickYourNumber":"Pilih Nomor Anda",
        "quickPlay":"Main Cepat",
        "viewYourNumber":"Lihat Nomor Anda",
        "entry":"Pilih jenis entri Anda di bawah",
        "play":"Mainkan",
        "oneTimeEntry":"Entri Satu Kali",
        "lines":"Baris",
        "selectLanguage":"Pilih Bahasa Anda:",
        "english":"Inggris",
        "chinese":"Cina",
        "korean":"Korea",
        "japanese":"Jepang",
        "vietnamese":"Vietnam",
        "filipino":"Filipina",
        "malay":"Melayu",
        "hindi":"Hindi",
        "indonesia":"Bahasa Indonesia",
        "chooseImage":"Ganti Gambar",
        "changePassword":"Ubah Kata Sandi",
        "deleteAccount":"Hapus Akun",
        "saveChanges":"Simpan Perubahan",
        "submit":"Kirim",
        "aboutTitle":"Tentang Kami",
        "languageTitle":"Bahasa",
        "userTransactionDone":"Pengguna Selesai melakukan transaksi",
        "ticketsTitle":"Tiket",
        "myWallet":"Dompet Saya",
        "myAccount":"Akun Saya",
        "logout":"Keluar",
        "createAccount":"Buat Akun",
        "logIn":"Masuk",
        "emailPaceholder":"Surel",
        "forgotPassword":"Lupa Kata Sandi",
        "million":"Jutaan",
        "fullName":"Nama Lengkap",
        "userTransactionCancel":"Pengguna Membatalkan transaksi",
        "confirmPassword":"Konfirmasi Kata Sandi",
        "signUp":"Daftar",
        "alreadyAccount":"Sudah memiliki akun",
        "forgotHeading":"Masukkan email yang Anda gunakan untuk login ke Lottery dan kami akan mengirimkan tautan untuk masuk kembali ke akun Anda.",
        "couponCode":"Kode Kupon",
        "applyCoupon":"Terapkan Kupon",
        "symbol":"$",
        "priceSummary":"Ringkasan Harga",
        "subTotal":"Subtotal",
        "discount":"Diskon",
        "serviceFee":"Biaya Layanan",
        "total":"Total",
        "waiting_msg":"Undian ini telah berakhir. Mohon tunggu undian berikutnya."
     }
});
export default StringsOfLanguages;


export const lang = [
    { shortform: 'en-US', longform: 'EnglishUS' },
    { shortform: 'en', longform: 'English' },
    { shortform: 'it', longform: 'Italic' },
];